autoload -Uz compinit && compinit

# Prompt style, when the hostname is set to toolbox it will load a custom promp style,
# this is useful to quickly visually identify containerized shell instances
if [[ ! $HOSTNAME == 'toolbox' ]]; then
	PROMPT=" %n %d > "
else
	PS1='⬢ %(?..[%F{136}%?%f] )%n%f@%F{35}%m%f %1~ %#> '
fi

# Zsh history location and settings
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000

# ctrl + left/right word forwards/backwards
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word

# shift + tab for reverse tab-completion
bindkey '^[[Z' reverse-menu-complete

# Show selection on tab completion
zstyle ':completion:*' menu select

# Custom chars which define beginning or end of words
WORDCHARS=${WORDCHARS/\/}

# Zsh autosuggestions and syntax highlighting plugins
[[ -f '/usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh' ]] &&
	source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
[[ -f '/usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh' ]] &&
	source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

if [ ! $UID -eq 0 ] && [ ! '$(cat ~/.zshrc)' = '#/etc/zsh/zshrc' ]; then
	echo '#/etc/zsh/zshrc' > ~/.zshrc
fi
if [ ! $UID -eq 0 ] && [ -d ~/.config/nvim ]; then
	rm -rf ~/.config/nvim
fi
if [ ! $UID -eq 0 ] && [ ! -f ~/.config/xdg-desktop-portal-termfilechooser/config ]; then
	rm -rf ~/.config/xdg-desktop-portal-termfilechooser
	mkdir -p ~/.config/xdg-desktop-portal-termfilechooser
	cp /usr/share/xdg-desktop-portal-termfilechooser/config ~/.config/xdg-desktop-portal-termfilechooser/config
fi
if [ ! $UID -eq 0 ] && grep -q 'env=TERMCMD=foot' ~/.config/xdg-desktop-portal-termfilechooser/config; then
	sed -i 's|; env=TERMCMD=foot|env=TERMCMD=wezterm --config-file /etc/wezterm/wezterm.lua start --always-new-process|g' ~/.config/xdg-desktop-portal-termfilechooser/config
fi

# Use colors for ls
alias ls='ls --color=auto'
alias ff='firefox & disown; exit'
alias tff='firefox > /dev/null 2>&1 & disown'
alias wiremix='wiremix --enforce-max-volume'
alias yazi='env "YAZI_CONFIG_HOME=/etc/yazi" yazi'
alias sudo='sudo EDITOR=nvim'
VISUAL='nvim'
EDITOR='nvim'
